name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./ASCAN-app/app
          file: ./ASCAN-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Kubernetes cluster
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install app ./iac/addons/app/helm \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/app \
            --set image.tag=latest -n app \
          
      - name: Update image
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gawk
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
          mkdir -p $HOME/.kube
          KUBECONFIG_FILE="$HOME/.kube/config"
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $KUBECONFIG_FILE
          export KUBECONFIG=$KUBECONFIG_FILE
          echo "Reiniciando o Deployment para atualizar a imagem..."
          kubectl rollout restart deployment app-deployment -n app
          